//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoBelediyeV22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstekSikayet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IstekSikayet()
        {
            this.Evrak = new HashSet<Evrak>();
            this.Foto = new HashSet<Foto>();
            this.Video = new HashSet<Video>();
            this.Video1 = new HashSet<Video>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int Istek_ID { get; set; }
        public Nullable<int> SosYetkili_ID { get; set; }
        public int Kullanıcı_ID { get; set; }
        public string Konu { get; set; }
        public string Desc { get; set; }
        public string Tarih { get; set; }
        public string Turu { get; set; }
        public string Yayinlansinmi { get; set; }
        public string Onay_Durum { get; set; }
        public Nullable<int> Adres_ID { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evrak> Evrak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual SosyalMedyaEkibi SosyalMedyaEkibi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Video1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
