//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoBelediyeV22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int Mesaj_ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public Nullable<int> SosMedyaYetkili_ID { get; set; }
        public string Konu { get; set; }
        public string Desc { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual SosyalMedyaEkibi SosyalMedyaEkibi { get; set; }
    }
}
