//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoBelediyeV22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int Yorum_ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public Nullable<int> Yetkili_ID { get; set; }
        public string YorumDesc { get; set; }
        public int Likee { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> Adres_ID { get; set; }
        public Nullable<int> IstekSikayet_ID { get; set; }
        public Nullable<int> foto_id { get; set; }
        public Nullable<int> video_id { get; set; }
        public Nullable<int> SosMedyaEkip_ID { get; set; }
        public string Onay_Durum { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Foto Foto { get; set; }
        public virtual IstekSikayet IstekSikayet { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual SosyalMedyaEkibi SosyalMedyaEkibi { get; set; }
        public virtual Video Video { get; set; }
    }
}
